package it.univr.rubikcube.gui;

import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import javax.swing.AbstractAction;
import javax.swing.ActionMap;
import javax.swing.InputMap;
import javax.swing.JComponent;
import javax.swing.KeyStroke;

/**
 * Forms to configure the number of faces.
 * @author Mattia Zago
 */
public class NumFaces extends javax.swing.JDialog {
    /**
     * A return status code - returned if Cancel button has been pressed.
     */
    public static final boolean RET_CANCEL = false;
    /**
     * A return status code - returned if OK button has been pressed.
     */
    public static final boolean RET_OK = true;
    /**
     * Default UID used for serialization.
     */
    private static final long serialVersionUID = 1L;
    /**
     * Default return status.
     */
    private boolean returnStatus = RET_CANCEL;
    /**
     * Number of selected faces.
     */
    private int selectedFaces = 3;
    /**
     * Creates a new instance of the form.
     * @param parent Parent window.
     * @param modal Specifies if the window should be modal or not.
     */
    public NumFaces(final java.awt.Frame parent, final boolean modal) {
        super(parent, modal);
        this.initComponents();
        setLocationRelativeTo(parent);
        // Close the dialog when Esc is pressed
        final String cancelName = "cancel";
        final InputMap inputMap = getRootPane().getInputMap(JComponent.WHEN_ANCESTOR_OF_FOCUSED_COMPONENT);
        inputMap.put(KeyStroke.getKeyStroke(KeyEvent.VK_ESCAPE, 0), cancelName);
        final ActionMap actionMap = getRootPane().getActionMap();
        actionMap.put(cancelName, new AbstractAction() {
            private static final long serialVersionUID = 1L;
            @Override
            public void actionPerformed(final ActionEvent e) {
                doClose(RET_CANCEL);
            }
        });
    }
    /**
     * Gets the return status for this window.
     * @return The return status of this dialog - one of RET_OK or RET_CANCEL
     */
    public final boolean getReturnStatus() {
        return this.returnStatus;
    }
    /**
     * Gets the number of selected faces.
     * @return The number of selected faces.
     */
    public final int getSelectedFaces() {
        return this.selectedFaces;
    }

    // CHECKSTYLE:OFF Rationale: autogenerated code
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        this.okButton = new javax.swing.JButton();
        this.cancelButton = new javax.swing.JButton();
        this.title = new javax.swing.JLabel();
        this.slider = new javax.swing.JSlider();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Edit number of faces");
        setAlwaysOnTop(true);
        setIconImage(null);
        setName("NumFaces"); // NOI18N
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        this.okButton.setText("OK");
        this.okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });

        this.cancelButton.setText("Cancel");
        this.cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        this.title.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        this.title.setLabelFor(this.slider);
        this.title.setText("Select number of faces");
        this.title.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        this.slider.setMajorTickSpacing(1);
        this.slider.setMaximum(6);
        this.slider.setMinimum(2);
        this.slider.setMinorTickSpacing(1);
        this.slider.setPaintLabels(true);
        this.slider.setPaintTicks(true);
        this.slider.setValue(3);
        this.slider.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        this.slider.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(this.okButton, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(this.cancelButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(this.slider, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(this.title, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(this.title)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(this.slider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(this.okButton)
                    .addComponent(this.cancelButton))
                .addContainerGap())
        );

        getRootPane().setDefaultButton(this.okButton);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
        this.selectedFaces = this.slider.getValue();
        doClose(RET_OK);
    }//GEN-LAST:event_okButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        doClose(RET_CANCEL);
    }//GEN-LAST:event_cancelButtonActionPerformed

    /**
     * Closes the dialog
     */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        doClose(RET_CANCEL);
    }//GEN-LAST:event_closeDialog
    // CHECKSTYLE:ON
    /**
     * Closes the window.
     * @param retStatus Return status.
     */
    final void doClose(final boolean retStatus) {
        this.returnStatus = retStatus;
        setVisible(false);
        dispose();
    }
    // CHECKSTYLE:OFF Rationale: autogenerated code
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButton;
    private javax.swing.JButton okButton;
    private javax.swing.JSlider slider;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
    // CHECKSTYLE:ON
}
